import { createClient } from '@sanity/client';
import { env } from '$env/dynamic/private';

export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		expiration: 30,
		allowQuery: []
	}
};

const client = createClient({
	projectId: env.SANITY_PROJECT_ID,
	dataset: env.SANITY_DATASET,
	useCdn: false,
	apiVersion: '2023-12-04'
});

/** @type {import('./$types').PageServerLoad} */
export async function load({ params }) {
	return {
		products: await client.fetch(
			'*[_type == "product"]{name, description, url, tags, "imageUrl": image.asset->url}'
		)
	};
}
